// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcAddMsg.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileType int32

const (
	FileType_FILE       FileType = 0
	FileType_LARGEFILE  FileType = 1
	FileType_DIRECTORY  FileType = 2
	FileType_SYSTEMLINK FileType = 3
)

var FileType_name = map[int32]string{
	0: "FILE",
	1: "LARGEFILE",
	2: "DIRECTORY",
	3: "SYSTEMLINK",
}
var FileType_value = map[string]int32{
	"FILE":       0,
	"LARGEFILE":  1,
	"DIRECTORY":  2,
	"SYSTEMLINK": 3,
}

func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}
func (FileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rpcAddMsg_3214063b6796f663, []int{0}
}

type Content struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpcAddMsg_3214063b6796f663, []int{0}
}
func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (dst *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(dst, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type AddRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FullPath             string   `protobuf:"bytes,2,opt,name=fullPath,proto3" json:"fullPath,omitempty"`
	FileSize             int32    `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	FileType             FileType `protobuf:"varint,4,opt,name=fileType,proto3,enum=pb.FileType" json:"fileType,omitempty"`
	FileData             []byte   `protobuf:"bytes,5,opt,name=fileData,proto3" json:"fileData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpcAddMsg_3214063b6796f663, []int{1}
}
func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (dst *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(dst, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *AddRequest) GetFullPath() string {
	if m != nil {
		return m.FullPath
	}
	return ""
}

func (m *AddRequest) GetFileSize() int32 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *AddRequest) GetFileType() FileType {
	if m != nil {
		return m.FileType
	}
	return FileType_FILE
}

func (m *AddRequest) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

type AddResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SessionId            string   `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpcAddMsg_3214063b6796f663, []int{2}
}
func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (dst *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(dst, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AddResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func init() {
	proto.RegisterType((*Content)(nil), "pb.Content")
	proto.RegisterType((*AddRequest)(nil), "pb.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "pb.AddResponse")
	proto.RegisterEnum("pb.FileType", FileType_name, FileType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddTaskClient is the client API for AddTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddTaskClient interface {
	AddFile(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	TransLargeFile(ctx context.Context, opts ...grpc.CallOption) (AddTask_TransLargeFileClient, error)
}

type addTaskClient struct {
	cc *grpc.ClientConn
}

func NewAddTaskClient(cc *grpc.ClientConn) AddTaskClient {
	return &addTaskClient{cc}
}

func (c *addTaskClient) AddFile(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/pb.AddTask/AddFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addTaskClient) TransLargeFile(ctx context.Context, opts ...grpc.CallOption) (AddTask_TransLargeFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AddTask_serviceDesc.Streams[0], "/pb.AddTask/TransLargeFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &addTaskTransLargeFileClient{stream}
	return x, nil
}

type AddTask_TransLargeFileClient interface {
	Send(*Content) error
	CloseAndRecv() (*AddResponse, error)
	grpc.ClientStream
}

type addTaskTransLargeFileClient struct {
	grpc.ClientStream
}

func (x *addTaskTransLargeFileClient) Send(m *Content) error {
	return x.ClientStream.SendMsg(m)
}

func (x *addTaskTransLargeFileClient) CloseAndRecv() (*AddResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AddResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AddTaskServer is the server API for AddTask service.
type AddTaskServer interface {
	AddFile(context.Context, *AddRequest) (*AddResponse, error)
	TransLargeFile(AddTask_TransLargeFileServer) error
}

func RegisterAddTaskServer(s *grpc.Server, srv AddTaskServer) {
	s.RegisterService(&_AddTask_serviceDesc, srv)
}

func _AddTask_AddFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddTaskServer).AddFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AddTask/AddFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddTaskServer).AddFile(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddTask_TransLargeFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AddTaskServer).TransLargeFile(&addTaskTransLargeFileServer{stream})
}

type AddTask_TransLargeFileServer interface {
	SendAndClose(*AddResponse) error
	Recv() (*Content, error)
	grpc.ServerStream
}

type addTaskTransLargeFileServer struct {
	grpc.ServerStream
}

func (x *addTaskTransLargeFileServer) SendAndClose(m *AddResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *addTaskTransLargeFileServer) Recv() (*Content, error) {
	m := new(Content)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AddTask_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AddTask",
	HandlerType: (*AddTaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFile",
			Handler:    _AddTask_AddFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransLargeFile",
			Handler:       _AddTask_TransLargeFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "rpcAddMsg.proto",
}

func init() { proto.RegisterFile("rpcAddMsg.proto", fileDescriptor_rpcAddMsg_3214063b6796f663) }

var fileDescriptor_rpcAddMsg_3214063b6796f663 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcb, 0xce, 0xda, 0x30,
	0x10, 0x85, 0x7f, 0x73, 0x29, 0x30, 0x40, 0x40, 0x5e, 0x45, 0xa8, 0x95, 0x50, 0xba, 0x89, 0xaa,
	0xca, 0xaa, 0xe8, 0x13, 0x04, 0x08, 0x55, 0x44, 0xa0, 0xc8, 0x64, 0xc3, 0xd2, 0x89, 0x5d, 0x1a,
	0x91, 0x5b, 0x63, 0xb3, 0x68, 0x1f, 0xa8, 0xcf, 0x59, 0xc5, 0xb9, 0xb0, 0xe9, 0x6e, 0xbe, 0x39,
	0x33, 0x93, 0x33, 0x19, 0xc3, 0xa2, 0x2c, 0x22, 0x87, 0xf3, 0x93, 0xbc, 0x93, 0xa2, 0xcc, 0x55,
	0x8e, 0x7b, 0x45, 0x68, 0x7d, 0x84, 0xd1, 0x2e, 0xcf, 0x94, 0xc8, 0x14, 0x36, 0x61, 0x14, 0xd5,
	0xa1, 0x89, 0xd6, 0xc8, 0x9e, 0xd1, 0x16, 0xad, 0xbf, 0x08, 0xc0, 0xe1, 0x9c, 0x8a, 0x5f, 0x4f,
	0x21, 0x15, 0x5e, 0xc1, 0xf8, 0x47, 0x9c, 0x88, 0x33, 0x4b, 0x85, 0xae, 0x9c, 0xd0, 0x8e, 0xb5,
	0xf6, 0x4c, 0x92, 0x0b, 0x53, 0x3f, 0xcd, 0x5e, 0xa3, 0x35, 0xdc, 0xf6, 0x5d, 0xe3, 0x3f, 0xc2,
	0xec, 0xaf, 0x91, 0x3d, 0xa4, 0x1d, 0x63, 0xbb, 0xd6, 0x82, 0xdf, 0x85, 0x30, 0x07, 0x6b, 0x64,
	0x1b, 0x9b, 0x19, 0x29, 0x42, 0x72, 0x68, 0x72, 0xb4, 0x53, 0xdb, 0x29, 0x7b, 0xa6, 0x98, 0x39,
	0xd4, 0x3e, 0x3b, 0xb6, 0x5c, 0x98, 0x6a, 0x9f, 0xb2, 0xc8, 0x33, 0x29, 0xaa, 0x8d, 0x52, 0x21,
	0x25, 0xbb, 0xb7, 0x3e, 0x5b, 0xc4, 0xef, 0x61, 0x22, 0x85, 0x94, 0x71, 0x9e, 0x79, 0xbc, 0xf1,
	0xf9, 0x4a, 0x7c, 0xda, 0xc2, 0xb8, 0xfd, 0x30, 0x1e, 0xc3, 0xe0, 0xe0, 0xf9, 0xee, 0xf2, 0x0d,
	0xcf, 0x61, 0xe2, 0x3b, 0xf4, 0x9b, 0xab, 0x11, 0x55, 0xb8, 0xf7, 0xa8, 0xbb, 0x0b, 0xbe, 0xd3,
	0xdb, 0xb2, 0x87, 0x0d, 0x80, 0xeb, 0xed, 0x1a, 0xb8, 0x27, 0xdf, 0x3b, 0x1f, 0x97, 0xfd, 0xcd,
	0x03, 0x46, 0x0e, 0xe7, 0x01, 0x93, 0x0f, 0xfc, 0x59, 0x87, 0xd5, 0x44, 0x6c, 0x54, 0x4b, 0xbd,
	0x7e, 0xe5, 0x6a, 0xd1, 0x71, 0x6d, 0xd9, 0x7a, 0xc3, 0x1b, 0x30, 0x82, 0x92, 0x65, 0xd2, 0x67,
	0xe5, 0x5d, 0xe8, 0xa6, 0x69, 0x55, 0xd4, 0x5c, 0xe9, 0x3f, 0x1d, 0x36, 0xda, 0x7e, 0x81, 0x0f,
	0x51, 0x9e, 0x92, 0x2c, 0x94, 0x24, 0xcb, 0xb9, 0x20, 0x4f, 0x15, 0x27, 0x92, 0x44, 0x29, 0x3f,
	0xc6, 0x4a, 0x92, 0x22, 0xdc, 0xce, 0x69, 0x7d, 0xfb, 0x7a, 0xfd, 0x0b, 0x0a, 0xdf, 0xe9, 0x27,
	0xf0, 0xf5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0x8b, 0x9a, 0xbb, 0x15, 0x02, 0x00, 0x00,
}
