// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcAddMsg.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileType int32

const (
	FileType_FILE       FileType = 0
	FileType_DIRECTORY  FileType = 1
	FileType_SYSTEMLINK FileType = 2
)

var FileType_name = map[int32]string{
	0: "FILE",
	1: "DIRECTORY",
	2: "SYSTEMLINK",
}
var FileType_value = map[string]int32{
	"FILE":       0,
	"DIRECTORY":  1,
	"SYSTEMLINK": 2,
}

func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}
func (FileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rpcAddMsg_1b94d364deb88008, []int{0}
}

type AddRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FullPath             string   `protobuf:"bytes,2,opt,name=fullPath,proto3" json:"fullPath,omitempty"`
	FileData             []byte   `protobuf:"bytes,3,opt,name=fileData,proto3" json:"fileData,omitempty"`
	FileType             FileType `protobuf:"varint,4,opt,name=fileType,proto3,enum=pb.FileType" json:"fileType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpcAddMsg_1b94d364deb88008, []int{0}
}
func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (dst *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(dst, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *AddRequest) GetFullPath() string {
	if m != nil {
		return m.FullPath
	}
	return ""
}

func (m *AddRequest) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

func (m *AddRequest) GetFileType() FileType {
	if m != nil {
		return m.FileType
	}
	return FileType_FILE
}

type AddResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpcAddMsg_1b94d364deb88008, []int{1}
}
func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (dst *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(dst, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "pb.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "pb.AddResponse")
	proto.RegisterEnum("pb.FileType", FileType_name, FileType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddTaskClient is the client API for AddTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddTaskClient interface {
	AddFile(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type addTaskClient struct {
	cc *grpc.ClientConn
}

func NewAddTaskClient(cc *grpc.ClientConn) AddTaskClient {
	return &addTaskClient{cc}
}

func (c *addTaskClient) AddFile(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/pb.AddTask/AddFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddTaskServer is the server API for AddTask service.
type AddTaskServer interface {
	AddFile(context.Context, *AddRequest) (*AddResponse, error)
}

func RegisterAddTaskServer(s *grpc.Server, srv AddTaskServer) {
	s.RegisterService(&_AddTask_serviceDesc, srv)
}

func _AddTask_AddFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddTaskServer).AddFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AddTask/AddFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddTaskServer).AddFile(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddTask_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AddTask",
	HandlerType: (*AddTaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFile",
			Handler:    _AddTask_AddFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcAddMsg.proto",
}

func init() { proto.RegisterFile("rpcAddMsg.proto", fileDescriptor_rpcAddMsg_1b94d364deb88008) }

var fileDescriptor_rpcAddMsg_1b94d364deb88008 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x4b, 0x6b, 0xf2, 0x40,
	0x18, 0x85, 0x1d, 0x3f, 0xf9, 0xd4, 0xb7, 0x1a, 0xc3, 0xac, 0x82, 0x50, 0x08, 0xd9, 0x34, 0x94,
	0x32, 0x14, 0x5d, 0x74, 0x1d, 0x6b, 0x84, 0xe0, 0xa5, 0x32, 0x66, 0xe3, 0x72, 0x92, 0x99, 0xda,
	0xd0, 0x5c, 0xa6, 0xce, 0x64, 0xd1, 0xbf, 0xd0, 0x5f, 0x5d, 0xcc, 0xad, 0xbb, 0x79, 0xe6, 0x70,
	0x5e, 0x1e, 0x0e, 0xcc, 0xae, 0x32, 0xf6, 0x38, 0xdf, 0xab, 0x0b, 0x91, 0xd7, 0x42, 0x17, 0xb8,
	0x2f, 0x23, 0xe7, 0x07, 0x01, 0x78, 0x9c, 0x53, 0xf1, 0x55, 0x0a, 0xa5, 0xf1, 0x1c, 0x46, 0xef,
	0x49, 0x2a, 0x0e, 0x2c, 0x13, 0x16, 0xb2, 0x91, 0x3b, 0xa6, 0x1d, 0x57, 0x59, 0x99, 0xa6, 0x47,
	0xa6, 0x3f, 0xac, 0x7e, 0x93, 0x35, 0xdc, 0xf6, 0xd6, 0x4c, 0x33, 0xeb, 0x9f, 0x8d, 0xdc, 0x09,
	0xed, 0x18, 0xbb, 0x75, 0x16, 0x7e, 0x4b, 0x61, 0x0d, 0x6c, 0xe4, 0x1a, 0x8b, 0x09, 0x91, 0x11,
	0xd9, 0x34, 0x7f, 0xb4, 0x4b, 0x9d, 0x07, 0xb8, 0xab, 0x5c, 0x94, 0x2c, 0x72, 0x25, 0xb0, 0x05,
	0xc3, 0x4c, 0x28, 0xc5, 0x2e, 0xad, 0x4b, 0x8b, 0x8f, 0x4b, 0x18, 0xb5, 0x75, 0x3c, 0x82, 0xc1,
	0x26, 0xd8, 0xf9, 0x66, 0x0f, 0x4f, 0x61, 0xbc, 0x0e, 0xa8, 0xff, 0x1a, 0xbe, 0xd1, 0xb3, 0x89,
	0xb0, 0x01, 0x70, 0x3a, 0x9f, 0x42, 0x7f, 0xbf, 0x0b, 0x0e, 0x5b, 0xb3, 0xbf, 0x78, 0x81, 0xa1,
	0xc7, 0x79, 0xc8, 0xd4, 0x27, 0x7e, 0xaa, 0x9e, 0xb7, 0x13, 0xd8, 0xb8, 0xb9, 0xfc, 0x2d, 0x30,
	0x9f, 0x75, 0x5c, 0x5b, 0x38, 0xbd, 0xd5, 0x33, 0xdc, 0xc7, 0x45, 0x46, 0xf2, 0x48, 0x91, 0xbc,
	0xe0, 0x82, 0x94, 0x3a, 0x49, 0x15, 0x89, 0x33, 0xbe, 0x4d, 0xb4, 0x22, 0x32, 0x5a, 0x4d, 0x69,
	0xbd, 0x6c, 0x6d, 0x77, 0x44, 0xd1, 0xff, 0x6a, 0xe0, 0xe5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x8d, 0x48, 0xba, 0x19, 0x73, 0x01, 0x00, 0x00,
}
