// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcGossipMessage.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartRequest struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ab5a21919ebadf9, []int{0}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

type StartResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ab5a21919ebadf9, []int{1}
}

func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (m *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(m, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

func (m *StartResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type StopRequest struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ab5a21919ebadf9, []int{2}
}

func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (m *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(m, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

func (m *StopRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

type StopResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ab5a21919ebadf9, []int{3}
}

func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (m *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(m, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

func (m *StopResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type DebugCmd struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebugCmd) Reset()         { *m = DebugCmd{} }
func (m *DebugCmd) String() string { return proto.CompactTextString(m) }
func (*DebugCmd) ProtoMessage()    {}
func (*DebugCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ab5a21919ebadf9, []int{4}
}

func (m *DebugCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugCmd.Unmarshal(m, b)
}
func (m *DebugCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugCmd.Marshal(b, m, deterministic)
}
func (m *DebugCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugCmd.Merge(m, src)
}
func (m *DebugCmd) XXX_Size() int {
	return xxx_messageInfo_DebugCmd.Size(m)
}
func (m *DebugCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugCmd.DiscardUnknown(m)
}

var xxx_messageInfo_DebugCmd proto.InternalMessageInfo

func (m *DebugCmd) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

type ViewInfos struct {
	Views                []string `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewInfos) Reset()         { *m = ViewInfos{} }
func (m *ViewInfos) String() string { return proto.CompactTextString(m) }
func (*ViewInfos) ProtoMessage()    {}
func (*ViewInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ab5a21919ebadf9, []int{5}
}

func (m *ViewInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewInfos.Unmarshal(m, b)
}
func (m *ViewInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewInfos.Marshal(b, m, deterministic)
}
func (m *ViewInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewInfos.Merge(m, src)
}
func (m *ViewInfos) XXX_Size() int {
	return xxx_messageInfo_ViewInfos.Size(m)
}
func (m *ViewInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewInfos.DiscardUnknown(m)
}

var xxx_messageInfo_ViewInfos proto.InternalMessageInfo

func (m *ViewInfos) GetViews() []string {
	if m != nil {
		return m.Views
	}
	return nil
}

type DebugResult struct {
	InputViews           *ViewInfos `protobuf:"bytes,1,opt,name=inputViews,proto3" json:"inputViews,omitempty"`
	OutputViews          *ViewInfos `protobuf:"bytes,2,opt,name=outputViews,proto3" json:"outputViews,omitempty"`
	Result               string     `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DebugResult) Reset()         { *m = DebugResult{} }
func (m *DebugResult) String() string { return proto.CompactTextString(m) }
func (*DebugResult) ProtoMessage()    {}
func (*DebugResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ab5a21919ebadf9, []int{6}
}

func (m *DebugResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugResult.Unmarshal(m, b)
}
func (m *DebugResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugResult.Marshal(b, m, deterministic)
}
func (m *DebugResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugResult.Merge(m, src)
}
func (m *DebugResult) XXX_Size() int {
	return xxx_messageInfo_DebugResult.Size(m)
}
func (m *DebugResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugResult.DiscardUnknown(m)
}

var xxx_messageInfo_DebugResult proto.InternalMessageInfo

func (m *DebugResult) GetInputViews() *ViewInfos {
	if m != nil {
		return m.InputViews
	}
	return nil
}

func (m *DebugResult) GetOutputViews() *ViewInfos {
	if m != nil {
		return m.OutputViews
	}
	return nil
}

func (m *DebugResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*StartRequest)(nil), "pb.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "pb.StartResponse")
	proto.RegisterType((*StopRequest)(nil), "pb.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "pb.StopResponse")
	proto.RegisterType((*DebugCmd)(nil), "pb.DebugCmd")
	proto.RegisterType((*ViewInfos)(nil), "pb.viewInfos")
	proto.RegisterType((*DebugResult)(nil), "pb.DebugResult")
}

func init() { proto.RegisterFile("rpcGossipMessage.proto", fileDescriptor_2ab5a21919ebadf9) }

var fileDescriptor_2ab5a21919ebadf9 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xd1, 0x4a, 0xf3, 0x30,
	0x14, 0xc7, 0x97, 0x8d, 0x8d, 0x6f, 0xa7, 0x1b, 0xeb, 0x17, 0x64, 0x8c, 0x21, 0x38, 0x73, 0xa1,
	0xbd, 0x31, 0xc2, 0xc4, 0x17, 0x98, 0x82, 0x78, 0x21, 0x48, 0x26, 0xde, 0x2f, 0x5d, 0x1c, 0xc5,
	0xb5, 0x89, 0x3d, 0xe9, 0x7c, 0x02, 0x1f, 0xc4, 0x37, 0x95, 0xb4, 0x5d, 0x0d, 0x32, 0xf1, 0xae,
	0xff, 0xf4, 0x97, 0x7f, 0x38, 0x3f, 0x0e, 0x8c, 0x73, 0x13, 0xdf, 0x69, 0xc4, 0xc4, 0x3c, 0x28,
	0xc4, 0xd5, 0x46, 0x71, 0x93, 0x6b, 0xab, 0x69, 0xdb, 0x48, 0x36, 0x83, 0xc1, 0xd2, 0xae, 0x72,
	0x2b, 0xd4, 0x5b, 0xa1, 0xd0, 0xd2, 0x10, 0x3a, 0x71, 0xba, 0x9e, 0x90, 0x19, 0x89, 0xfa, 0xc2,
	0x7d, 0xb2, 0x73, 0x18, 0xd6, 0x04, 0x1a, 0x9d, 0xa1, 0xa2, 0x63, 0xe8, 0xe5, 0x0a, 0x8b, 0xad,
	0xad, 0xa9, 0x3a, 0xb1, 0x13, 0x08, 0x96, 0x56, 0x9b, 0xdf, 0x9b, 0xce, 0xdc, 0x5b, 0x0e, 0xf8,
	0xa3, 0xe8, 0x18, 0xfe, 0xdd, 0x2a, 0x59, 0x6c, 0x6e, 0xd2, 0xf5, 0x81, 0x96, 0x53, 0xe8, 0xef,
	0x12, 0xf5, 0x7e, 0x9f, 0xbd, 0x68, 0xa4, 0x47, 0xd0, 0x75, 0x01, 0x27, 0x64, 0xd6, 0x89, 0xfa,
	0xa2, 0x0a, 0xec, 0x83, 0x40, 0x50, 0x36, 0x88, 0xb2, 0x90, 0x5e, 0x00, 0x24, 0x99, 0x29, 0xec,
	0x73, 0x8d, 0x92, 0x28, 0x98, 0x0f, 0xb9, 0x91, 0xbc, 0x29, 0x12, 0x1e, 0x40, 0x2f, 0x21, 0xd0,
	0x85, 0x6d, 0xf8, 0xf6, 0x21, 0xde, 0x27, 0xbc, 0x41, 0x3a, 0xfe, 0x20, 0xf3, 0x4f, 0x02, 0x50,
	0x89, 0x7f, 0x5a, 0xe1, 0x2b, 0xbd, 0x86, 0x01, 0x3a, 0x93, 0x4b, 0x95, 0xef, 0x92, 0x58, 0xd1,
	0xd0, 0x55, 0xfa, 0xf6, 0xa7, 0xff, 0xbd, 0x93, 0x4a, 0x12, 0x6b, 0xd1, 0x39, 0x04, 0x68, 0xb5,
	0xd9, 0xdf, 0x1a, 0x55, 0x4c, 0x23, 0x7a, 0x1a, 0x7e, 0x1f, 0x34, 0x77, 0x22, 0xe8, 0xae, 0x9d,
	0x00, 0x3a, 0x70, 0x3f, 0xf7, 0x36, 0xa7, 0xa3, 0x26, 0x55, 0x66, 0x58, 0x6b, 0x11, 0x01, 0x8d,
	0x75, 0xca, 0x33, 0x89, 0x3c, 0xd6, 0x19, 0xea, 0xad, 0xe2, 0x46, 0x2e, 0x42, 0xf1, 0x63, 0x65,
	0x1e, 0x89, 0xec, 0x95, 0x5b, 0x73, 0xf5, 0x15, 0x00, 0x00, 0xff, 0xff, 0x65, 0xfa, 0x63, 0x55,
	0x4f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GossipTaskClient is the client API for GossipTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GossipTaskClient interface {
	StartService(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	StopService(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	Debug(ctx context.Context, in *DebugCmd, opts ...grpc.CallOption) (*DebugResult, error)
}

type gossipTaskClient struct {
	cc *grpc.ClientConn
}

func NewGossipTaskClient(cc *grpc.ClientConn) GossipTaskClient {
	return &gossipTaskClient{cc}
}

func (c *gossipTaskClient) StartService(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/pb.GossipTask/startService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipTaskClient) StopService(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, "/pb.GossipTask/stopService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipTaskClient) Debug(ctx context.Context, in *DebugCmd, opts ...grpc.CallOption) (*DebugResult, error) {
	out := new(DebugResult)
	err := c.cc.Invoke(ctx, "/pb.GossipTask/debug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GossipTaskServer is the server API for GossipTask service.
type GossipTaskServer interface {
	StartService(context.Context, *StartRequest) (*StartResponse, error)
	StopService(context.Context, *StopRequest) (*StopResponse, error)
	Debug(context.Context, *DebugCmd) (*DebugResult, error)
}

func RegisterGossipTaskServer(s *grpc.Server, srv GossipTaskServer) {
	s.RegisterService(&_GossipTask_serviceDesc, srv)
}

func _GossipTask_StartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipTaskServer).StartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GossipTask/StartService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipTaskServer).StartService(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GossipTask_StopService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipTaskServer).StopService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GossipTask/StopService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipTaskServer).StopService(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GossipTask_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugCmd)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipTaskServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GossipTask/Debug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipTaskServer).Debug(ctx, req.(*DebugCmd))
	}
	return interceptor(ctx, in, info, handler)
}

var _GossipTask_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GossipTask",
	HandlerType: (*GossipTaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "startService",
			Handler:    _GossipTask_StartService_Handler,
		},
		{
			MethodName: "stopService",
			Handler:    _GossipTask_StopService_Handler,
		},
		{
			MethodName: "debug",
			Handler:    _GossipTask_Debug_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcGossipMessage.proto",
}
