// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcGetMessage.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	DataUri              string   `protobuf:"bytes,1,opt,name=dataUri,proto3" json:"dataUri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4017a178f96b5b2b, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetDataUri() string {
	if m != nil {
		return m.DataUri
	}
	return ""
}

type GetResponse struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4017a178f96b5b2b, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "pb.GetResponse")
}

func init() { proto.RegisterFile("rpcGetMessage.proto", fileDescriptor_4017a178f96b5b2b) }

var fileDescriptor_4017a178f96b5b2b = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xcb, 0x8a, 0x02, 0x31,
	0x10, 0x45, 0x27, 0x33, 0x30, 0x8d, 0xe5, 0x0b, 0xe2, 0xa6, 0x71, 0x25, 0x0d, 0x3e, 0x70, 0x11,
	0x44, 0xf1, 0x07, 0x7a, 0x93, 0x95, 0x20, 0x41, 0x3f, 0x20, 0x89, 0x85, 0x88, 0x9a, 0xc4, 0xae,
	0xf2, 0xff, 0xc5, 0x96, 0x56, 0x97, 0x07, 0x0e, 0xf7, 0x1e, 0x18, 0x54, 0xc9, 0x6b, 0xe4, 0x0d,
	0x12, 0xd9, 0x23, 0xaa, 0x54, 0x45, 0x8e, 0xf2, 0x37, 0xb9, 0x62, 0x02, 0xa0, 0x91, 0x0d, 0xde,
	0xee, 0x48, 0x2c, 0x73, 0xc8, 0x0e, 0x96, 0xed, 0xbe, 0x3a, 0xe5, 0x62, 0x24, 0x66, 0x2d, 0xd3,
	0x60, 0x31, 0x85, 0x76, 0xed, 0x51, 0x8a, 0x81, 0xf0, 0x29, 0xfa, 0x18, 0x18, 0x03, 0xd7, 0x62,
	0xc7, 0x34, 0xb8, 0x5c, 0x43, 0xa6, 0x91, 0x77, 0x96, 0xce, 0x72, 0x0e, 0x7f, 0x1a, 0x59, 0xf6,
	0x54, 0x72, 0xea, 0x73, 0x32, 0xec, 0xbf, 0xf9, 0x35, 0x56, 0xfc, 0x2c, 0x44, 0x39, 0x06, 0xe9,
	0xe3, 0x55, 0x05, 0x47, 0xca, 0xc7, 0x40, 0xf1, 0x82, 0x2a, 0xb9, 0xb2, 0x6b, 0xbe, 0xb3, 0xb7,
	0xc2, 0xfd, 0xd7, 0xe5, 0xab, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x45, 0x39, 0xe8, 0xd0,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetTaskClient is the client API for GetTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetTaskClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (GetTask_GetClient, error)
}

type getTaskClient struct {
	cc *grpc.ClientConn
}

func NewGetTaskClient(cc *grpc.ClientConn) GetTaskClient {
	return &getTaskClient{cc}
}

func (c *getTaskClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (GetTask_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GetTask_serviceDesc.Streams[0], "/pb.GetTask/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &getTaskGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GetTask_GetClient interface {
	Recv() (*GetResponse, error)
	grpc.ClientStream
}

type getTaskGetClient struct {
	grpc.ClientStream
}

func (x *getTaskGetClient) Recv() (*GetResponse, error) {
	m := new(GetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GetTaskServer is the server API for GetTask service.
type GetTaskServer interface {
	Get(*GetRequest, GetTask_GetServer) error
}

func RegisterGetTaskServer(s *grpc.Server, srv GetTaskServer) {
	s.RegisterService(&_GetTask_serviceDesc, srv)
}

func _GetTask_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GetTaskServer).Get(m, &getTaskGetServer{stream})
}

type GetTask_GetServer interface {
	Send(*GetResponse) error
	grpc.ServerStream
}

type getTaskGetServer struct {
	grpc.ServerStream
}

func (x *getTaskGetServer) Send(m *GetResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _GetTask_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GetTask",
	HandlerType: (*GetTaskServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _GetTask_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpcGetMessage.proto",
}
