// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcNatMsg.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NatStatusResQuest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NatStatusResQuest) Reset()         { *m = NatStatusResQuest{} }
func (m *NatStatusResQuest) String() string { return proto.CompactTextString(m) }
func (*NatStatusResQuest) ProtoMessage()    {}
func (*NatStatusResQuest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a389f0335330cfee, []int{0}
}

func (m *NatStatusResQuest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatStatusResQuest.Unmarshal(m, b)
}
func (m *NatStatusResQuest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatStatusResQuest.Marshal(b, m, deterministic)
}
func (m *NatStatusResQuest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatStatusResQuest.Merge(m, src)
}
func (m *NatStatusResQuest) XXX_Size() int {
	return xxx_messageInfo_NatStatusResQuest.Size(m)
}
func (m *NatStatusResQuest) XXX_DiscardUnknown() {
	xxx_messageInfo_NatStatusResQuest.DiscardUnknown(m)
}

var xxx_messageInfo_NatStatusResQuest proto.InternalMessageInfo

func (m *NatStatusResQuest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type NatStatusResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NatStatusResponse) Reset()         { *m = NatStatusResponse{} }
func (m *NatStatusResponse) String() string { return proto.CompactTextString(m) }
func (*NatStatusResponse) ProtoMessage()    {}
func (*NatStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a389f0335330cfee, []int{1}
}

func (m *NatStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatStatusResponse.Unmarshal(m, b)
}
func (m *NatStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatStatusResponse.Marshal(b, m, deterministic)
}
func (m *NatStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatStatusResponse.Merge(m, src)
}
func (m *NatStatusResponse) XXX_Size() int {
	return xxx_messageInfo_NatStatusResponse.Size(m)
}
func (m *NatStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NatStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NatStatusResponse proto.InternalMessageInfo

func (m *NatStatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*NatStatusResQuest)(nil), "pb.NatStatusResQuest")
	proto.RegisterType((*NatStatusResponse)(nil), "pb.NatStatusResponse")
}

func init() { proto.RegisterFile("rpcNatMsg.proto", fileDescriptor_a389f0335330cfee) }

var fileDescriptor_a389f0335330cfee = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x41, 0x0b, 0x82, 0x40,
	0x10, 0x85, 0xb3, 0x43, 0xe6, 0x42, 0x44, 0x0b, 0x81, 0x78, 0x0a, 0x21, 0xe8, 0xd2, 0x06, 0x75,
	0xec, 0xe6, 0xa1, 0x5b, 0x52, 0xd6, 0x1f, 0x98, 0xb5, 0xc5, 0x43, 0xe9, 0x0c, 0xce, 0x48, 0x7f,
	0x3f, 0xd0, 0x12, 0xc2, 0xe3, 0x1b, 0xe6, 0xbd, 0x8f, 0x4f, 0xcd, 0x6b, 0xca, 0x53, 0x90, 0x33,
	0x17, 0x86, 0x6a, 0x14, 0xd4, 0x63, 0xb2, 0xf1, 0x4e, 0x2d, 0x52, 0x90, 0x9b, 0x80, 0x34, 0x9c,
	0x39, 0xbe, 0x36, 0x8e, 0x45, 0x47, 0x6a, 0x4a, 0xc0, 0xfc, 0xc6, 0xfa, 0x11, 0x7a, 0x2b, 0x6f,
	0x13, 0x64, 0x7d, 0x8e, 0xb7, 0xff, 0x05, 0xc2, 0x8a, 0x9d, 0x0e, 0x95, 0x5f, 0x3a, 0x66, 0x28,
	0xdc, 0xf7, 0xff, 0x17, 0xf7, 0x27, 0xe5, 0xa7, 0x20, 0x77, 0xe0, 0xa7, 0x3e, 0xaa, 0xa0, 0x6f,
	0xea, 0xa5, 0x21, 0x6b, 0x06, 0xe4, 0x68, 0x70, 0x6e, 0xf7, 0xe3, 0x51, 0xb2, 0x56, 0x3a, 0xc7,
	0xd2, 0x54, 0x96, 0x4d, 0x8e, 0x15, 0xe3, 0xcb, 0x19, 0xb2, 0xc9, 0x2c, 0xeb, 0x94, 0x3a, 0xd8,
	0xc5, 0xb3, 0x93, 0xd6, 0xec, 0xf0, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x47, 0x06, 0xdc, 0xec,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NatTaskClient is the client API for NatTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NatTaskClient interface {
	NatStatus(ctx context.Context, in *NatStatusResQuest, opts ...grpc.CallOption) (*NatStatusResponse, error)
}

type natTaskClient struct {
	cc *grpc.ClientConn
}

func NewNatTaskClient(cc *grpc.ClientConn) NatTaskClient {
	return &natTaskClient{cc}
}

func (c *natTaskClient) NatStatus(ctx context.Context, in *NatStatusResQuest, opts ...grpc.CallOption) (*NatStatusResponse, error) {
	out := new(NatStatusResponse)
	err := c.cc.Invoke(ctx, "/pb.NatTask/NatStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NatTaskServer is the server API for NatTask service.
type NatTaskServer interface {
	NatStatus(context.Context, *NatStatusResQuest) (*NatStatusResponse, error)
}

func RegisterNatTaskServer(s *grpc.Server, srv NatTaskServer) {
	s.RegisterService(&_NatTask_serviceDesc, srv)
}

func _NatTask_NatStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NatStatusResQuest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NatTaskServer).NatStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NatTask/NatStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NatTaskServer).NatStatus(ctx, req.(*NatStatusResQuest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NatTask_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NatTask",
	HandlerType: (*NatTaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NatStatus",
			Handler:    _NatTask_NatStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcNatMsg.proto",
}
