// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connectInvite.proto

package nat_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InviteRequest struct {
	FromPeerId           string   `protobuf:"bytes,1,opt,name=FromPeerId,proto3" json:"FromPeerId,omitempty"`
	ToPeerId             string   `protobuf:"bytes,2,opt,name=ToPeerId,proto3" json:"ToPeerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteRequest) Reset()         { *m = InviteRequest{} }
func (m *InviteRequest) String() string { return proto.CompactTextString(m) }
func (*InviteRequest) ProtoMessage()    {}
func (*InviteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10a401791c40cd, []int{0}
}

func (m *InviteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteRequest.Unmarshal(m, b)
}
func (m *InviteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteRequest.Marshal(b, m, deterministic)
}
func (m *InviteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteRequest.Merge(m, src)
}
func (m *InviteRequest) XXX_Size() int {
	return xxx_messageInfo_InviteRequest.Size(m)
}
func (m *InviteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteRequest proto.InternalMessageInfo

func (m *InviteRequest) GetFromPeerId() string {
	if m != nil {
		return m.FromPeerId
	}
	return ""
}

func (m *InviteRequest) GetToPeerId() string {
	if m != nil {
		return m.ToPeerId
	}
	return ""
}

type InviteResponse struct {
	PeerId               string   `protobuf:"bytes,2,opt,name=peerId,proto3" json:"peerId,omitempty"`
	PublicIp             string   `protobuf:"bytes,3,opt,name=publicIp,proto3" json:"publicIp,omitempty"`
	PublicPort           int32    `protobuf:"varint,4,opt,name=publicPort,proto3" json:"publicPort,omitempty"`
	PrivateIp            string   `protobuf:"bytes,5,opt,name=privateIp,proto3" json:"privateIp,omitempty"`
	PrivatePort          int32    `protobuf:"varint,6,opt,name=privatePort,proto3" json:"privatePort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteResponse) Reset()         { *m = InviteResponse{} }
func (m *InviteResponse) String() string { return proto.CompactTextString(m) }
func (*InviteResponse) ProtoMessage()    {}
func (*InviteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10a401791c40cd, []int{1}
}

func (m *InviteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteResponse.Unmarshal(m, b)
}
func (m *InviteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteResponse.Marshal(b, m, deterministic)
}
func (m *InviteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteResponse.Merge(m, src)
}
func (m *InviteResponse) XXX_Size() int {
	return xxx_messageInfo_InviteResponse.Size(m)
}
func (m *InviteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InviteResponse proto.InternalMessageInfo

func (m *InviteResponse) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *InviteResponse) GetPublicIp() string {
	if m != nil {
		return m.PublicIp
	}
	return ""
}

func (m *InviteResponse) GetPublicPort() int32 {
	if m != nil {
		return m.PublicPort
	}
	return 0
}

func (m *InviteResponse) GetPrivateIp() string {
	if m != nil {
		return m.PrivateIp
	}
	return ""
}

func (m *InviteResponse) GetPrivatePort() int32 {
	if m != nil {
		return m.PrivatePort
	}
	return 0
}

func init() {
	proto.RegisterType((*InviteRequest)(nil), "nat.pb.InviteRequest")
	proto.RegisterType((*InviteResponse)(nil), "nat.pb.inviteResponse")
}

func init() { proto.RegisterFile("connectInvite.proto", fileDescriptor_bf10a401791c40cd) }

var fileDescriptor_bf10a401791c40cd = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0xcb,
	0x4b, 0x4d, 0x2e, 0xf1, 0xcc, 0x2b, 0xcb, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0xcb, 0x4b, 0x2c, 0xd1, 0x2b, 0x48, 0x52, 0xf2, 0xe6, 0xe2, 0x85, 0x88, 0x07, 0xa5, 0x16,
	0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x71, 0x71, 0xb9, 0x15, 0xe5, 0xe7, 0x06, 0xa4, 0xa6, 0x16,
	0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x89, 0x08, 0x49, 0x71, 0x71, 0x84,
	0xe4, 0x43, 0x65, 0x99, 0xc0, 0xb2, 0x70, 0xbe, 0xd2, 0x12, 0x46, 0x2e, 0xbe, 0x4c, 0xa8, 0x69,
	0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x62, 0x5c, 0x6c, 0x05, 0xc8, 0x8a, 0xa1, 0x3c, 0x90,
	0x31, 0x05, 0xa5, 0x49, 0x39, 0x99, 0xc9, 0x9e, 0x05, 0x12, 0xcc, 0x10, 0x63, 0x60, 0x7c, 0x90,
	0x13, 0x20, 0xec, 0x80, 0xfc, 0xa2, 0x12, 0x09, 0x16, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x24, 0x11,
	0x21, 0x19, 0x2e, 0xce, 0x82, 0xa2, 0xcc, 0xb2, 0xc4, 0x92, 0x54, 0xcf, 0x02, 0x09, 0x56, 0xb0,
	0x66, 0x84, 0x80, 0x90, 0x02, 0x17, 0x37, 0x94, 0x03, 0xd6, 0xce, 0x06, 0xd6, 0x8e, 0x2c, 0x94,
	0xc4, 0x06, 0x0e, 0x02, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xbd, 0x7f, 0xf4, 0x19,
	0x01, 0x00, 0x00,
}
