// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deNatSys.proto

package net_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeSysMsgType int32

const (
	DeSysMsgType_Unknown      DeSysMsgType = 0
	DeSysMsgType_ServiceReg   DeSysMsgType = 1
	DeSysMsgType_FindPeerById DeSysMsgType = 2
)

var DeSysMsgType_name = map[int32]string{
	0: "Unknown",
	1: "ServiceReg",
	2: "FindPeerById",
}

var DeSysMsgType_value = map[string]int32{
	"Unknown":      0,
	"ServiceReg":   1,
	"FindPeerById": 2,
}

func (x DeSysMsgType) String() string {
	return proto.EnumName(DeSysMsgType_name, int32(x))
}

func (DeSysMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_af622bf53b9d481d, []int{0}
}

type DeNatSysReq struct {
	NatSerId             string   `protobuf:"bytes,1,opt,name=natSerId,proto3" json:"natSerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeNatSysReq) Reset()         { *m = DeNatSysReq{} }
func (m *DeNatSysReq) String() string { return proto.CompactTextString(m) }
func (*DeNatSysReq) ProtoMessage()    {}
func (*DeNatSysReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_af622bf53b9d481d, []int{0}
}

func (m *DeNatSysReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeNatSysReq.Unmarshal(m, b)
}
func (m *DeNatSysReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeNatSysReq.Marshal(b, m, deterministic)
}
func (m *DeNatSysReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeNatSysReq.Merge(m, src)
}
func (m *DeNatSysReq) XXX_Size() int {
	return xxx_messageInfo_DeNatSysReq.Size(m)
}
func (m *DeNatSysReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeNatSysReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeNatSysReq proto.InternalMessageInfo

func (m *DeNatSysReq) GetNatSerId() string {
	if m != nil {
		return m.NatSerId
	}
	return ""
}

type DeNatSysRsp struct {
	NatSerId             string   `protobuf:"bytes,1,opt,name=natSerId,proto3" json:"natSerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeNatSysRsp) Reset()         { *m = DeNatSysRsp{} }
func (m *DeNatSysRsp) String() string { return proto.CompactTextString(m) }
func (*DeNatSysRsp) ProtoMessage()    {}
func (*DeNatSysRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_af622bf53b9d481d, []int{1}
}

func (m *DeNatSysRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeNatSysRsp.Unmarshal(m, b)
}
func (m *DeNatSysRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeNatSysRsp.Marshal(b, m, deterministic)
}
func (m *DeNatSysRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeNatSysRsp.Merge(m, src)
}
func (m *DeNatSysRsp) XXX_Size() int {
	return xxx_messageInfo_DeNatSysRsp.Size(m)
}
func (m *DeNatSysRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeNatSysRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DeNatSysRsp proto.InternalMessageInfo

func (m *DeNatSysRsp) GetNatSerId() string {
	if m != nil {
		return m.NatSerId
	}
	return ""
}

func init() {
	proto.RegisterEnum("net.pb.DeSysMsgType", DeSysMsgType_name, DeSysMsgType_value)
	proto.RegisterType((*DeNatSysReq)(nil), "net.pb.DeNatSysReq")
	proto.RegisterType((*DeNatSysRsp)(nil), "net.pb.DeNatSysRsp")
}

func init() { proto.RegisterFile("deNatSys.proto", fileDescriptor_af622bf53b9d481d) }

var fileDescriptor_af622bf53b9d481d = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x49, 0xf5, 0x4b,
	0x2c, 0x09, 0xae, 0x2c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0x4b, 0x2d, 0xd1,
	0x2b, 0x48, 0x52, 0xd2, 0xe4, 0xe2, 0x76, 0x81, 0xca, 0x04, 0xa5, 0x16, 0x0a, 0x49, 0x71, 0x71,
	0xe4, 0x25, 0x96, 0x04, 0xa7, 0x16, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1,
	0xf9, 0x28, 0x4a, 0x8b, 0x0b, 0xf0, 0x29, 0xd5, 0xb2, 0xe5, 0xe2, 0x49, 0x49, 0x0d, 0xae, 0x2c,
	0xf6, 0x2d, 0x4e, 0x0f, 0xa9, 0x2c, 0x48, 0x15, 0xe2, 0xe6, 0x62, 0x0f, 0xcd, 0xcb, 0xce, 0xcb,
	0x2f, 0xcf, 0x13, 0x60, 0x10, 0xe2, 0xe3, 0xe2, 0x0a, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x0d,
	0x4a, 0x4d, 0x17, 0x60, 0x14, 0x12, 0xe0, 0xe2, 0x71, 0xcb, 0xcc, 0x4b, 0x09, 0x48, 0x4d, 0x2d,
	0x72, 0xaa, 0xf4, 0x4c, 0x11, 0x60, 0x4a, 0x62, 0x03, 0xbb, 0xd1, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x9f, 0x8a, 0x0f, 0xe9, 0xb5, 0x00, 0x00, 0x00,
}
