// Code generated by protoc-gen-go. DO NOT EDIT.
// source: natManager.proto

package net_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NatMsgType int32

const (
	NatMsgType_UnknownReq   NatMsgType = 0
	NatMsgType_BootStrapReg NatMsgType = 1
	NatMsgType_KeepAlive    NatMsgType = 2
	NatMsgType_Connect      NatMsgType = 3
	NatMsgType_Ping         NatMsgType = 4
	NatMsgType_error        NatMsgType = 5
)

var NatMsgType_name = map[int32]string{
	0: "UnknownReq",
	1: "BootStrapReg",
	2: "KeepAlive",
	3: "Connect",
	4: "Ping",
	5: "error",
}

var NatMsgType_value = map[string]int32{
	"UnknownReq":   0,
	"BootStrapReg": 1,
	"KeepAlive":    2,
	"Connect":      3,
	"Ping":         4,
	"error":        5,
}

func (x NatMsgType) String() string {
	return proto.EnumName(NatMsgType_name, int32(x))
}

func (NatMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2f5cc5a30f7d4657, []int{0}
}

type NatType int32

const (
	NatType_UnknownRES     NatType = 0
	NatType_NoNatDevice    NatType = 1
	NatType_BehindNat      NatType = 2
	NatType_CanBeNatServer NatType = 3
	NatType_ToBeChecked    NatType = 4
)

var NatType_name = map[int32]string{
	0: "UnknownRES",
	1: "NoNatDevice",
	2: "BehindNat",
	3: "CanBeNatServer",
	4: "ToBeChecked",
}

var NatType_value = map[string]int32{
	"UnknownRES":     0,
	"NoNatDevice":    1,
	"BehindNat":      2,
	"CanBeNatServer": 3,
	"ToBeChecked":    4,
}

func (x NatType) String() string {
	return proto.EnumName(NatType_name, int32(x))
}

func (NatType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2f5cc5a30f7d4657, []int{1}
}

type BootNatRegReq struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	PrivatePort          string   `protobuf:"bytes,3,opt,name=privatePort,proto3" json:"privatePort,omitempty"`
	PrivateIp            string   `protobuf:"bytes,2,opt,name=privateIp,proto3" json:"privateIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootNatRegReq) Reset()         { *m = BootNatRegReq{} }
func (m *BootNatRegReq) String() string { return proto.CompactTextString(m) }
func (*BootNatRegReq) ProtoMessage()    {}
func (*BootNatRegReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f5cc5a30f7d4657, []int{0}
}

func (m *BootNatRegReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootNatRegReq.Unmarshal(m, b)
}
func (m *BootNatRegReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootNatRegReq.Marshal(b, m, deterministic)
}
func (m *BootNatRegReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootNatRegReq.Merge(m, src)
}
func (m *BootNatRegReq) XXX_Size() int {
	return xxx_messageInfo_BootNatRegReq.Size(m)
}
func (m *BootNatRegReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BootNatRegReq.DiscardUnknown(m)
}

var xxx_messageInfo_BootNatRegReq proto.InternalMessageInfo

func (m *BootNatRegReq) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *BootNatRegReq) GetPrivatePort() string {
	if m != nil {
		return m.PrivatePort
	}
	return ""
}

func (m *BootNatRegReq) GetPrivateIp() string {
	if m != nil {
		return m.PrivateIp
	}
	return ""
}

type BootNatRegRes struct {
	NatType              NatType  `protobuf:"varint,1,opt,name=natType,proto3,enum=net.pb.NatType" json:"natType,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	PublicIp             string   `protobuf:"bytes,3,opt,name=publicIp,proto3" json:"publicIp,omitempty"`
	PublicPort           string   `protobuf:"bytes,4,opt,name=publicPort,proto3" json:"publicPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootNatRegRes) Reset()         { *m = BootNatRegRes{} }
func (m *BootNatRegRes) String() string { return proto.CompactTextString(m) }
func (*BootNatRegRes) ProtoMessage()    {}
func (*BootNatRegRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f5cc5a30f7d4657, []int{1}
}

func (m *BootNatRegRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootNatRegRes.Unmarshal(m, b)
}
func (m *BootNatRegRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootNatRegRes.Marshal(b, m, deterministic)
}
func (m *BootNatRegRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootNatRegRes.Merge(m, src)
}
func (m *BootNatRegRes) XXX_Size() int {
	return xxx_messageInfo_BootNatRegRes.Size(m)
}
func (m *BootNatRegRes) XXX_DiscardUnknown() {
	xxx_messageInfo_BootNatRegRes.DiscardUnknown(m)
}

var xxx_messageInfo_BootNatRegRes proto.InternalMessageInfo

func (m *BootNatRegRes) GetNatType() NatType {
	if m != nil {
		return m.NatType
	}
	return NatType_UnknownRES
}

func (m *BootNatRegRes) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *BootNatRegRes) GetPublicIp() string {
	if m != nil {
		return m.PublicIp
	}
	return ""
}

func (m *BootNatRegRes) GetPublicPort() string {
	if m != nil {
		return m.PublicPort
	}
	return ""
}

type NatConReq struct {
	FromPeerId           string   `protobuf:"bytes,1,opt,name=FromPeerId,proto3" json:"FromPeerId,omitempty"`
	ToPeerId             string   `protobuf:"bytes,2,opt,name=ToPeerId,proto3" json:"ToPeerId,omitempty"`
	ToPort               int32    `protobuf:"varint,3,opt,name=ToPort,proto3" json:"ToPort,omitempty"`
	SessionId            string   `protobuf:"bytes,4,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NatConReq) Reset()         { *m = NatConReq{} }
func (m *NatConReq) String() string { return proto.CompactTextString(m) }
func (*NatConReq) ProtoMessage()    {}
func (*NatConReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f5cc5a30f7d4657, []int{2}
}

func (m *NatConReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatConReq.Unmarshal(m, b)
}
func (m *NatConReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatConReq.Marshal(b, m, deterministic)
}
func (m *NatConReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatConReq.Merge(m, src)
}
func (m *NatConReq) XXX_Size() int {
	return xxx_messageInfo_NatConReq.Size(m)
}
func (m *NatConReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NatConReq.DiscardUnknown(m)
}

var xxx_messageInfo_NatConReq proto.InternalMessageInfo

func (m *NatConReq) GetFromPeerId() string {
	if m != nil {
		return m.FromPeerId
	}
	return ""
}

func (m *NatConReq) GetToPeerId() string {
	if m != nil {
		return m.ToPeerId
	}
	return ""
}

func (m *NatConReq) GetToPort() int32 {
	if m != nil {
		return m.ToPort
	}
	return 0
}

func (m *NatConReq) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type NatConRes struct {
	PeerId               string   `protobuf:"bytes,2,opt,name=peerId,proto3" json:"peerId,omitempty"`
	PublicIp             string   `protobuf:"bytes,3,opt,name=publicIp,proto3" json:"publicIp,omitempty"`
	PublicPort           string   `protobuf:"bytes,4,opt,name=publicPort,proto3" json:"publicPort,omitempty"`
	PrivateIp            string   `protobuf:"bytes,5,opt,name=privateIp,proto3" json:"privateIp,omitempty"`
	PrivatePort          string   `protobuf:"bytes,6,opt,name=privatePort,proto3" json:"privatePort,omitempty"`
	SessionId            string   `protobuf:"bytes,7,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	CanServe             bool     `protobuf:"varint,8,opt,name=canServe,proto3" json:"canServe,omitempty"`
	TargetPort           int32    `protobuf:"varint,9,opt,name=targetPort,proto3" json:"targetPort,omitempty"`
	IsCaller             bool     `protobuf:"varint,10,opt,name=isCaller,proto3" json:"isCaller,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NatConRes) Reset()         { *m = NatConRes{} }
func (m *NatConRes) String() string { return proto.CompactTextString(m) }
func (*NatConRes) ProtoMessage()    {}
func (*NatConRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f5cc5a30f7d4657, []int{3}
}

func (m *NatConRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatConRes.Unmarshal(m, b)
}
func (m *NatConRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatConRes.Marshal(b, m, deterministic)
}
func (m *NatConRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatConRes.Merge(m, src)
}
func (m *NatConRes) XXX_Size() int {
	return xxx_messageInfo_NatConRes.Size(m)
}
func (m *NatConRes) XXX_DiscardUnknown() {
	xxx_messageInfo_NatConRes.DiscardUnknown(m)
}

var xxx_messageInfo_NatConRes proto.InternalMessageInfo

func (m *NatConRes) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *NatConRes) GetPublicIp() string {
	if m != nil {
		return m.PublicIp
	}
	return ""
}

func (m *NatConRes) GetPublicPort() string {
	if m != nil {
		return m.PublicPort
	}
	return ""
}

func (m *NatConRes) GetPrivateIp() string {
	if m != nil {
		return m.PrivateIp
	}
	return ""
}

func (m *NatConRes) GetPrivatePort() string {
	if m != nil {
		return m.PrivatePort
	}
	return ""
}

func (m *NatConRes) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *NatConRes) GetCanServe() bool {
	if m != nil {
		return m.CanServe
	}
	return false
}

func (m *NatConRes) GetTargetPort() int32 {
	if m != nil {
		return m.TargetPort
	}
	return 0
}

func (m *NatConRes) GetIsCaller() bool {
	if m != nil {
		return m.IsCaller
	}
	return false
}

type NatKeepAlive struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NatKeepAlive) Reset()         { *m = NatKeepAlive{} }
func (m *NatKeepAlive) String() string { return proto.CompactTextString(m) }
func (*NatKeepAlive) ProtoMessage()    {}
func (*NatKeepAlive) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f5cc5a30f7d4657, []int{4}
}

func (m *NatKeepAlive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatKeepAlive.Unmarshal(m, b)
}
func (m *NatKeepAlive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatKeepAlive.Marshal(b, m, deterministic)
}
func (m *NatKeepAlive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatKeepAlive.Merge(m, src)
}
func (m *NatKeepAlive) XXX_Size() int {
	return xxx_messageInfo_NatKeepAlive.Size(m)
}
func (m *NatKeepAlive) XXX_DiscardUnknown() {
	xxx_messageInfo_NatKeepAlive.DiscardUnknown(m)
}

var xxx_messageInfo_NatKeepAlive proto.InternalMessageInfo

func (m *NatKeepAlive) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type NatPing struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	Pong                 string   `protobuf:"bytes,2,opt,name=pong,proto3" json:"pong,omitempty"`
	Nonce                string   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TTL                  int32    `protobuf:"varint,4,opt,name=TTL,proto3" json:"TTL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NatPing) Reset()         { *m = NatPing{} }
func (m *NatPing) String() string { return proto.CompactTextString(m) }
func (*NatPing) ProtoMessage()    {}
func (*NatPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f5cc5a30f7d4657, []int{5}
}

func (m *NatPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatPing.Unmarshal(m, b)
}
func (m *NatPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatPing.Marshal(b, m, deterministic)
}
func (m *NatPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatPing.Merge(m, src)
}
func (m *NatPing) XXX_Size() int {
	return xxx_messageInfo_NatPing.Size(m)
}
func (m *NatPing) XXX_DiscardUnknown() {
	xxx_messageInfo_NatPing.DiscardUnknown(m)
}

var xxx_messageInfo_NatPing proto.InternalMessageInfo

func (m *NatPing) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

func (m *NatPing) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

func (m *NatPing) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *NatPing) GetTTL() int32 {
	if m != nil {
		return m.TTL
	}
	return 0
}

type ErrorNotify struct {
	ErrMsg               string   `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorNotify) Reset()         { *m = ErrorNotify{} }
func (m *ErrorNotify) String() string { return proto.CompactTextString(m) }
func (*ErrorNotify) ProtoMessage()    {}
func (*ErrorNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f5cc5a30f7d4657, []int{6}
}

func (m *ErrorNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorNotify.Unmarshal(m, b)
}
func (m *ErrorNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorNotify.Marshal(b, m, deterministic)
}
func (m *ErrorNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorNotify.Merge(m, src)
}
func (m *ErrorNotify) XXX_Size() int {
	return xxx_messageInfo_ErrorNotify.Size(m)
}
func (m *ErrorNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorNotify proto.InternalMessageInfo

func (m *ErrorNotify) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type NatRequest struct {
	MsgType              NatMsgType     `protobuf:"varint,1,opt,name=msgType,proto3,enum=net.pb.NatMsgType" json:"msgType,omitempty"`
	BootRegReq           *BootNatRegReq `protobuf:"bytes,2,opt,name=BootRegReq,proto3" json:"BootRegReq,omitempty"`
	ConnReq              *NatConReq     `protobuf:"bytes,3,opt,name=connReq,proto3" json:"connReq,omitempty"`
	KeepAlive            *NatKeepAlive  `protobuf:"bytes,4,opt,name=keepAlive,proto3" json:"keepAlive,omitempty"`
	Ping                 *NatPing       `protobuf:"bytes,5,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NatRequest) Reset()         { *m = NatRequest{} }
func (m *NatRequest) String() string { return proto.CompactTextString(m) }
func (*NatRequest) ProtoMessage()    {}
func (*NatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f5cc5a30f7d4657, []int{7}
}

func (m *NatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatRequest.Unmarshal(m, b)
}
func (m *NatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatRequest.Marshal(b, m, deterministic)
}
func (m *NatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatRequest.Merge(m, src)
}
func (m *NatRequest) XXX_Size() int {
	return xxx_messageInfo_NatRequest.Size(m)
}
func (m *NatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NatRequest proto.InternalMessageInfo

func (m *NatRequest) GetMsgType() NatMsgType {
	if m != nil {
		return m.MsgType
	}
	return NatMsgType_UnknownReq
}

func (m *NatRequest) GetBootRegReq() *BootNatRegReq {
	if m != nil {
		return m.BootRegReq
	}
	return nil
}

func (m *NatRequest) GetConnReq() *NatConReq {
	if m != nil {
		return m.ConnReq
	}
	return nil
}

func (m *NatRequest) GetKeepAlive() *NatKeepAlive {
	if m != nil {
		return m.KeepAlive
	}
	return nil
}

func (m *NatRequest) GetPing() *NatPing {
	if m != nil {
		return m.Ping
	}
	return nil
}

type Response struct {
	MsgType              NatMsgType     `protobuf:"varint,1,opt,name=msgType,proto3,enum=net.pb.NatMsgType" json:"msgType,omitempty"`
	BootRegRes           *BootNatRegRes `protobuf:"bytes,2,opt,name=BootRegRes,proto3" json:"BootRegRes,omitempty"`
	ConnRes              *NatConRes     `protobuf:"bytes,3,opt,name=connRes,proto3" json:"connRes,omitempty"`
	KeepAlive            *NatKeepAlive  `protobuf:"bytes,4,opt,name=keepAlive,proto3" json:"keepAlive,omitempty"`
	Pong                 *NatPing       `protobuf:"bytes,5,opt,name=pong,proto3" json:"pong,omitempty"`
	Error                *ErrorNotify   `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f5cc5a30f7d4657, []int{8}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsgType() NatMsgType {
	if m != nil {
		return m.MsgType
	}
	return NatMsgType_UnknownReq
}

func (m *Response) GetBootRegRes() *BootNatRegRes {
	if m != nil {
		return m.BootRegRes
	}
	return nil
}

func (m *Response) GetConnRes() *NatConRes {
	if m != nil {
		return m.ConnRes
	}
	return nil
}

func (m *Response) GetKeepAlive() *NatKeepAlive {
	if m != nil {
		return m.KeepAlive
	}
	return nil
}

func (m *Response) GetPong() *NatPing {
	if m != nil {
		return m.Pong
	}
	return nil
}

func (m *Response) GetError() *ErrorNotify {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterEnum("net.pb.NatMsgType", NatMsgType_name, NatMsgType_value)
	proto.RegisterEnum("net.pb.NatType", NatType_name, NatType_value)
	proto.RegisterType((*BootNatRegReq)(nil), "net.pb.BootNatRegReq")
	proto.RegisterType((*BootNatRegRes)(nil), "net.pb.BootNatRegRes")
	proto.RegisterType((*NatConReq)(nil), "net.pb.NatConReq")
	proto.RegisterType((*NatConRes)(nil), "net.pb.NatConRes")
	proto.RegisterType((*NatKeepAlive)(nil), "net.pb.NatKeepAlive")
	proto.RegisterType((*NatPing)(nil), "net.pb.NatPing")
	proto.RegisterType((*ErrorNotify)(nil), "net.pb.ErrorNotify")
	proto.RegisterType((*NatRequest)(nil), "net.pb.NatRequest")
	proto.RegisterType((*Response)(nil), "net.pb.response")
}

func init() { proto.RegisterFile("natManager.proto", fileDescriptor_2f5cc5a30f7d4657) }

var fileDescriptor_2f5cc5a30f7d4657 = []byte{
	// 677 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xd3, 0x4a,
	0x14, 0x6d, 0x3e, 0x9c, 0xc4, 0xd7, 0xfd, 0xf0, 0x9b, 0xd7, 0xf7, 0x14, 0x21, 0x54, 0x55, 0x46,
	0xa0, 0xb6, 0xa0, 0x2c, 0x82, 0xf8, 0x01, 0x24, 0x14, 0x29, 0x82, 0x5a, 0x95, 0x1b, 0x16, 0x6c,
	0x40, 0x53, 0xe7, 0xe2, 0x5a, 0x4d, 0x67, 0xdc, 0x99, 0x69, 0x50, 0x17, 0xfc, 0x05, 0x76, 0xec,
	0xf9, 0x97, 0x6c, 0xd1, 0x8c, 0xc7, 0xce, 0x24, 0xa2, 0x5d, 0xd0, 0x9d, 0xef, 0xc7, 0xcc, 0x3d,
	0xe7, 0xcc, 0xb9, 0x32, 0x84, 0x8c, 0xaa, 0x13, 0xca, 0x68, 0x86, 0x62, 0x50, 0x08, 0xae, 0x38,
	0xe9, 0x30, 0x54, 0x83, 0xe2, 0x3c, 0xca, 0x60, 0x6b, 0xc4, 0xb9, 0x8a, 0xa9, 0x4a, 0x30, 0x4b,
	0xf0, 0x9a, 0xfc, 0x0f, 0x1d, 0xc6, 0x67, 0x38, 0x99, 0xf5, 0x1b, 0xfb, 0x8d, 0x03, 0x3f, 0xb1,
	0x11, 0xd9, 0x87, 0xa0, 0x10, 0xf9, 0x82, 0x2a, 0x3c, 0xe5, 0x42, 0xf5, 0x5b, 0xa6, 0xe8, 0xa6,
	0xc8, 0x63, 0xf0, 0x6d, 0x38, 0x29, 0xfa, 0x4d, 0x53, 0x5f, 0x26, 0xa2, 0xef, 0x8d, 0xd5, 0x49,
	0x92, 0x1c, 0x42, 0x97, 0x51, 0x35, 0xbd, 0x2d, 0xd0, 0x8c, 0xda, 0x1e, 0xee, 0x0c, 0x4a, 0x50,
	0x83, 0xb8, 0x4c, 0x27, 0x55, 0xdd, 0x01, 0xd5, 0x5c, 0x01, 0xf5, 0x08, 0x7a, 0xc5, 0xcd, 0xf9,
	0x3c, 0x4f, 0x27, 0x85, 0x45, 0x54, 0xc7, 0x64, 0x0f, 0xa0, 0xfc, 0x36, 0x78, 0xdb, 0xa6, 0xea,
	0x64, 0xa2, 0x6f, 0xe0, 0xc7, 0x54, 0x8d, 0x39, 0xd3, 0xac, 0xf7, 0x00, 0xde, 0x0a, 0x7e, 0x75,
	0x8a, 0x28, 0x6a, 0xe6, 0x4e, 0x46, 0x0f, 0x9a, 0x72, 0x5b, 0x2d, 0x21, 0xd4, 0xb1, 0x06, 0x37,
	0xe5, 0xb5, 0x28, 0x5e, 0x62, 0x23, 0xad, 0x87, 0x44, 0x29, 0x73, 0xce, 0x26, 0x33, 0x3b, 0x7f,
	0x99, 0x88, 0x7e, 0x34, 0x97, 0xf3, 0xa5, 0xbe, 0xa3, 0x70, 0x6f, 0xb7, 0xd1, 0x43, 0x08, 0xae,
	0xbe, 0x87, 0xb7, 0xf6, 0x1e, 0xeb, 0xef, 0xd9, 0xf9, 0xe3, 0x7b, 0x2e, 0xf1, 0x77, 0xd7, 0xf0,
	0x6b, 0x64, 0x29, 0x65, 0x67, 0x28, 0x16, 0xd8, 0xef, 0xed, 0x37, 0x0e, 0x7a, 0x49, 0x1d, 0x6b,
	0x64, 0x8a, 0x8a, 0x0c, 0x95, 0xb9, 0xda, 0x37, 0xaa, 0x38, 0x19, 0x7d, 0x36, 0x97, 0x63, 0x3a,
	0x9f, 0xa3, 0xe8, 0x43, 0x79, 0xb6, 0x8a, 0xa3, 0x67, 0xb0, 0x19, 0x53, 0xf5, 0x0e, 0xb1, 0x78,
	0x3d, 0xcf, 0x17, 0x78, 0x97, 0x1f, 0xa3, 0x8f, 0xd0, 0x8d, 0xa9, 0x3a, 0xcd, 0x59, 0x46, 0x08,
	0xb4, 0x8b, 0x9c, 0x65, 0xb6, 0xc1, 0x7c, 0x9b, 0x1c, 0x67, 0x99, 0x95, 0xd3, 0x7c, 0x93, 0x5d,
	0xf0, 0x18, 0x67, 0x29, 0x5a, 0x25, 0xcb, 0x80, 0x84, 0xd0, 0x9a, 0x4e, 0xdf, 0x1b, 0xfd, 0xbc,
	0x44, 0x7f, 0x46, 0x4f, 0x21, 0x38, 0x16, 0x82, 0x8b, 0x98, 0xab, 0xfc, 0xcb, 0xad, 0x46, 0x80,
	0x42, 0x9c, 0xc8, 0x6a, 0x80, 0x8d, 0xa2, 0x5f, 0x0d, 0x00, 0xe3, 0xe6, 0xeb, 0x1b, 0x94, 0x8a,
	0xbc, 0x80, 0xee, 0x95, 0xcc, 0x1c, 0x3b, 0x13, 0xc7, 0xce, 0x27, 0x65, 0x25, 0xa9, 0x5a, 0xc8,
	0x2b, 0x00, 0xbd, 0x0d, 0xe5, 0xd2, 0x19, 0x94, 0xc1, 0xf0, 0xbf, 0xea, 0xc0, 0xca, 0x46, 0x26,
	0x4e, 0x23, 0x79, 0x0e, 0xdd, 0x94, 0x33, 0x6d, 0x59, 0x43, 0x22, 0x18, 0xfe, 0xe3, 0x0c, 0x29,
	0xbd, 0x9c, 0x54, 0x1d, 0x64, 0x08, 0xfe, 0x65, 0xa5, 0xa3, 0xe1, 0x17, 0x0c, 0x77, 0x9d, 0xf6,
	0x5a, 0xe3, 0x64, 0xd9, 0x46, 0x9e, 0x58, 0x2d, 0x3d, 0xd3, 0xee, 0x6e, 0xa4, 0x96, 0xba, 0x14,
	0x37, 0xfa, 0xd9, 0x84, 0x9e, 0x40, 0x59, 0x70, 0x26, 0xf1, 0x01, 0xbc, 0xe5, 0x7d, 0xbc, 0xa5,
	0xc3, 0x5b, 0x2e, 0x79, 0xcb, 0xbb, 0x78, 0xcb, 0x8a, 0xb7, 0xfc, 0x6b, 0xde, 0xfc, 0x3e, 0xde,
	0xda, 0x40, 0x87, 0xe0, 0xa1, 0x36, 0x86, 0xd9, 0x96, 0x60, 0xf8, 0x6f, 0xd5, 0xe5, 0xb8, 0x25,
	0x29, 0x3b, 0x8e, 0x3e, 0x1b, 0x6f, 0x58, 0xfa, 0x64, 0x1b, 0xe0, 0x03, 0xbb, 0x64, 0xfc, 0xab,
	0x7e, 0x97, 0x70, 0x83, 0x84, 0xb0, 0xa9, 0xc9, 0x9d, 0x29, 0x41, 0x8b, 0x04, 0xb3, 0xb0, 0x41,
	0xb6, 0xc0, 0xaf, 0x71, 0x85, 0x4d, 0x12, 0x40, 0x77, 0xcc, 0x19, 0xc3, 0x54, 0x85, 0x2d, 0xd2,
	0x83, 0xb6, 0x06, 0x11, 0xb6, 0x89, 0x6f, 0x01, 0x84, 0xde, 0xd1, 0x27, 0xe3, 0xff, 0xf5, 0xdb,
	0x8f, 0xcf, 0xc2, 0x0d, 0xb2, 0x03, 0x41, 0xcc, 0x63, 0xaa, 0xde, 0xe0, 0x22, 0x4f, 0xb1, 0xbc,
	0x7c, 0x84, 0x17, 0x39, 0x9b, 0xc5, 0x54, 0x85, 0x4d, 0x42, 0x60, 0x7b, 0x4c, 0xd9, 0x08, 0x63,
	0xaa, 0xcc, 0xbe, 0x8a, 0xb0, 0xa5, 0xcf, 0x4c, 0xf9, 0x08, 0xc7, 0x17, 0x98, 0x5e, 0xe2, 0x2c,
	0x6c, 0x9f, 0x77, 0xcc, 0x7f, 0xe2, 0xe5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xa2, 0x56,
	0x95, 0x3b, 0x06, 0x00, 0x00,
}
