// Code generated by protoc-gen-go. DO NOT EDIT.
// source: natRegister.proto

package nat_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegRequest struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	PrivatePort          int32    `protobuf:"varint,3,opt,name=privatePort,proto3" json:"privatePort,omitempty"`
	Zone                 string   `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	PrivateIp            string   `protobuf:"bytes,2,opt,name=privateIp,proto3" json:"privateIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegRequest) Reset()         { *m = RegRequest{} }
func (m *RegRequest) String() string { return proto.CompactTextString(m) }
func (*RegRequest) ProtoMessage()    {}
func (*RegRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fd0c039665f1e05, []int{0}
}

func (m *RegRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegRequest.Unmarshal(m, b)
}
func (m *RegRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegRequest.Marshal(b, m, deterministic)
}
func (m *RegRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegRequest.Merge(m, src)
}
func (m *RegRequest) XXX_Size() int {
	return xxx_messageInfo_RegRequest.Size(m)
}
func (m *RegRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegRequest proto.InternalMessageInfo

func (m *RegRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *RegRequest) GetPrivatePort() int32 {
	if m != nil {
		return m.PrivatePort
	}
	return 0
}

func (m *RegRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *RegRequest) GetPrivateIp() string {
	if m != nil {
		return m.PrivateIp
	}
	return ""
}

type RegResponse struct {
	IsAfterNat           bool     `protobuf:"varint,1,opt,name=isAfterNat,proto3" json:"isAfterNat,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	PublicIp             string   `protobuf:"bytes,3,opt,name=publicIp,proto3" json:"publicIp,omitempty"`
	PublicPort           int32    `protobuf:"varint,4,opt,name=publicPort,proto3" json:"publicPort,omitempty"`
	Zone                 string   `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegResponse) Reset()         { *m = RegResponse{} }
func (m *RegResponse) String() string { return proto.CompactTextString(m) }
func (*RegResponse) ProtoMessage()    {}
func (*RegResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fd0c039665f1e05, []int{1}
}

func (m *RegResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegResponse.Unmarshal(m, b)
}
func (m *RegResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegResponse.Marshal(b, m, deterministic)
}
func (m *RegResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegResponse.Merge(m, src)
}
func (m *RegResponse) XXX_Size() int {
	return xxx_messageInfo_RegResponse.Size(m)
}
func (m *RegResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegResponse proto.InternalMessageInfo

func (m *RegResponse) GetIsAfterNat() bool {
	if m != nil {
		return m.IsAfterNat
	}
	return false
}

func (m *RegResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *RegResponse) GetPublicIp() string {
	if m != nil {
		return m.PublicIp
	}
	return ""
}

func (m *RegResponse) GetPublicPort() int32 {
	if m != nil {
		return m.PublicPort
	}
	return 0
}

func (m *RegResponse) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func init() {
	proto.RegisterType((*RegRequest)(nil), "nat.pb.RegRequest")
	proto.RegisterType((*RegResponse)(nil), "nat.pb.RegResponse")
}

func init() { proto.RegisterFile("natRegister.proto", fileDescriptor_3fd0c039665f1e05) }

var fileDescriptor_3fd0c039665f1e05 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4a, 0xc7, 0x30,
	0x10, 0x85, 0xc9, 0xcf, 0xb6, 0xb4, 0xd3, 0x95, 0x59, 0x48, 0x10, 0x91, 0xd2, 0x55, 0x57, 0xdd,
	0x78, 0x02, 0x97, 0xdd, 0x88, 0xe4, 0x06, 0xa9, 0x1d, 0x4b, 0x40, 0x92, 0x98, 0x4c, 0x45, 0xbc,
	0x87, 0xf7, 0x15, 0xc7, 0xd2, 0xc6, 0xdd, 0xbc, 0x2f, 0x7f, 0xde, 0xc7, 0xc0, 0xb5, 0x33, 0xa4,
	0x71, 0xb5, 0x89, 0x30, 0x8e, 0x21, 0x7a, 0xf2, 0xb2, 0x72, 0x86, 0xc6, 0x30, 0xf7, 0x9f, 0x00,
	0x1a, 0x57, 0x8d, 0xef, 0x1b, 0x26, 0x92, 0x37, 0x50, 0x39, 0xbf, 0xe0, 0xb4, 0x28, 0xd1, 0x89,
	0xa1, 0xd1, 0x7b, 0x92, 0x1d, 0xb4, 0x21, 0xda, 0x0f, 0x43, 0xf8, 0xec, 0x23, 0xa9, 0xab, 0x4e,
	0x0c, 0xa5, 0xce, 0x91, 0x94, 0x50, 0x7c, 0x79, 0x87, 0xaa, 0xe0, 0x77, 0x3c, 0xcb, 0x3b, 0x68,
	0xf6, 0x2b, 0x53, 0x50, 0x17, 0x3e, 0x38, 0x41, 0xff, 0x2d, 0xa0, 0xe5, 0xea, 0x14, 0xbc, 0x4b,
	0x28, 0xef, 0x01, 0x6c, 0x7a, 0x7c, 0x25, 0x8c, 0x4f, 0x86, 0xb8, 0xbf, 0xd6, 0x19, 0xc9, 0xdc,
	0x2e, 0xff, 0xdc, 0x6e, 0xa1, 0x0e, 0xdb, 0xfc, 0x66, 0x5f, 0xa6, 0xc0, 0x62, 0x8d, 0x3e, 0xf2,
	0xef, 0x9f, 0x7f, 0x33, 0x6b, 0x17, 0xac, 0x9d, 0x91, 0xc3, 0xba, 0x3c, 0xad, 0xe7, 0x8a, 0x17,
	0xf4, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0x09, 0x12, 0x06, 0x30, 0x35, 0x01, 0x00, 0x00,
}
