// Code generated by protoc-gen-go. DO NOT EDIT.
// source: natRequest.proto

package nat_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NatRequest struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	PrivatePort          int32    `protobuf:"varint,3,opt,name=privatePort,proto3" json:"privatePort,omitempty"`
	Zone                 string   `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	PrivateIp            string   `protobuf:"bytes,2,opt,name=privateIp,proto3" json:"privateIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NatRequest) Reset()         { *m = NatRequest{} }
func (m *NatRequest) String() string { return proto.CompactTextString(m) }
func (*NatRequest) ProtoMessage()    {}
func (*NatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af675dd6ec799f3, []int{0}
}

func (m *NatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatRequest.Unmarshal(m, b)
}
func (m *NatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatRequest.Marshal(b, m, deterministic)
}
func (m *NatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatRequest.Merge(m, src)
}
func (m *NatRequest) XXX_Size() int {
	return xxx_messageInfo_NatRequest.Size(m)
}
func (m *NatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NatRequest proto.InternalMessageInfo

func (m *NatRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NatRequest) GetPrivatePort() int32 {
	if m != nil {
		return m.PrivatePort
	}
	return 0
}

func (m *NatRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *NatRequest) GetPrivateIp() string {
	if m != nil {
		return m.PrivateIp
	}
	return ""
}

type NatResponse struct {
	IsAfterNat           bool     `protobuf:"varint,1,opt,name=isAfterNat,proto3" json:"isAfterNat,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	PublicIp             string   `protobuf:"bytes,3,opt,name=publicIp,proto3" json:"publicIp,omitempty"`
	PublicPort           int32    `protobuf:"varint,4,opt,name=publicPort,proto3" json:"publicPort,omitempty"`
	Zone                 string   `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NatResponse) Reset()         { *m = NatResponse{} }
func (m *NatResponse) String() string { return proto.CompactTextString(m) }
func (*NatResponse) ProtoMessage()    {}
func (*NatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af675dd6ec799f3, []int{1}
}

func (m *NatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NatResponse.Unmarshal(m, b)
}
func (m *NatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NatResponse.Marshal(b, m, deterministic)
}
func (m *NatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NatResponse.Merge(m, src)
}
func (m *NatResponse) XXX_Size() int {
	return xxx_messageInfo_NatResponse.Size(m)
}
func (m *NatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NatResponse proto.InternalMessageInfo

func (m *NatResponse) GetIsAfterNat() bool {
	if m != nil {
		return m.IsAfterNat
	}
	return false
}

func (m *NatResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NatResponse) GetPublicIp() string {
	if m != nil {
		return m.PublicIp
	}
	return ""
}

func (m *NatResponse) GetPublicPort() int32 {
	if m != nil {
		return m.PublicPort
	}
	return 0
}

func (m *NatResponse) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func init() {
	proto.RegisterType((*NatRequest)(nil), "nat.pb.natRequest")
	proto.RegisterType((*NatResponse)(nil), "nat.pb.natResponse")
}

func init() { proto.RegisterFile("natRequest.proto", fileDescriptor_8af675dd6ec799f3) }

var fileDescriptor_8af675dd6ec799f3 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x8a, 0x83, 0x30,
	0x10, 0x86, 0x89, 0xab, 0xa2, 0xe3, 0x65, 0xc9, 0x61, 0x09, 0xcb, 0xb2, 0x88, 0x27, 0x4f, 0x5e,
	0xf6, 0x09, 0xf6, 0xe8, 0xa5, 0x94, 0xbc, 0x41, 0xac, 0x29, 0x08, 0x25, 0x49, 0x93, 0xb1, 0x94,
	0xbe, 0x47, 0xdf, 0xb7, 0x74, 0x2a, 0x9a, 0xde, 0x66, 0xbe, 0x3f, 0xc9, 0xff, 0x11, 0xf8, 0x34,
	0x0a, 0xa5, 0x3e, 0xcf, 0x3a, 0x60, 0xe7, 0xbc, 0x45, 0xcb, 0x73, 0xa3, 0xb0, 0x73, 0x43, 0x73,
	0x05, 0xd8, 0x32, 0xfe, 0x05, 0xb9, 0xb1, 0xa3, 0xee, 0x47, 0xc1, 0x6a, 0xd6, 0x96, 0x72, 0xd9,
	0x78, 0x0d, 0x95, 0xf3, 0xd3, 0x45, 0xa1, 0xde, 0x5b, 0x8f, 0xe2, 0xa3, 0x66, 0x6d, 0x26, 0x63,
	0xc4, 0x39, 0xa4, 0x37, 0x6b, 0xb4, 0x48, 0xe9, 0x1e, 0xcd, 0xfc, 0x07, 0xca, 0xe5, 0x48, 0xef,
	0x44, 0x42, 0xc1, 0x06, 0x9a, 0x3b, 0x83, 0x8a, 0xaa, 0x83, 0xb3, 0x26, 0x68, 0xfe, 0x0b, 0x30,
	0x85, 0xff, 0x23, 0x6a, 0xbf, 0x53, 0x48, 0xfd, 0x85, 0x8c, 0x48, 0xe4, 0x96, 0xbc, 0xb9, 0x7d,
	0x43, 0xe1, 0xe6, 0xe1, 0x34, 0x1d, 0x7a, 0x47, 0x62, 0xa5, 0x5c, 0xf7, 0xe7, 0x9b, 0xaf, 0x99,
	0xb4, 0x53, 0xd2, 0x8e, 0xc8, 0x6a, 0x9d, 0x6d, 0xd6, 0x43, 0x4e, 0x1f, 0xf4, 0xf7, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x13, 0x9b, 0x95, 0xa0, 0x34, 0x01, 0x00, 0x00,
}
