// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nbsAddr.proto

package net_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NbsAddr struct {
	NetworkId            string   `protobuf:"bytes,1,opt,name=networkId,proto3" json:"networkId,omitempty"`
	CanServer            bool     `protobuf:"varint,2,opt,name=canServer,proto3" json:"canServer,omitempty"`
	PubIp                string   `protobuf:"bytes,3,opt,name=pubIp,proto3" json:"pubIp,omitempty"`
	PubPort              int32    `protobuf:"varint,4,opt,name=pubPort,proto3" json:"pubPort,omitempty"`
	PriIp                string   `protobuf:"bytes,5,opt,name=priIp,proto3" json:"priIp,omitempty"`
	PriPort              int32    `protobuf:"varint,6,opt,name=priPort,proto3" json:"priPort,omitempty"`
	NatIP                string   `protobuf:"bytes,7,opt,name=natIP,proto3" json:"natIP,omitempty"`
	NatPort              int32    `protobuf:"varint,8,opt,name=natPort,proto3" json:"natPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NbsAddr) Reset()         { *m = NbsAddr{} }
func (m *NbsAddr) String() string { return proto.CompactTextString(m) }
func (*NbsAddr) ProtoMessage()    {}
func (*NbsAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_b059c628fec3ac7c, []int{0}
}

func (m *NbsAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NbsAddr.Unmarshal(m, b)
}
func (m *NbsAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NbsAddr.Marshal(b, m, deterministic)
}
func (m *NbsAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NbsAddr.Merge(m, src)
}
func (m *NbsAddr) XXX_Size() int {
	return xxx_messageInfo_NbsAddr.Size(m)
}
func (m *NbsAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_NbsAddr.DiscardUnknown(m)
}

var xxx_messageInfo_NbsAddr proto.InternalMessageInfo

func (m *NbsAddr) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

func (m *NbsAddr) GetCanServer() bool {
	if m != nil {
		return m.CanServer
	}
	return false
}

func (m *NbsAddr) GetPubIp() string {
	if m != nil {
		return m.PubIp
	}
	return ""
}

func (m *NbsAddr) GetPubPort() int32 {
	if m != nil {
		return m.PubPort
	}
	return 0
}

func (m *NbsAddr) GetPriIp() string {
	if m != nil {
		return m.PriIp
	}
	return ""
}

func (m *NbsAddr) GetPriPort() int32 {
	if m != nil {
		return m.PriPort
	}
	return 0
}

func (m *NbsAddr) GetNatIP() string {
	if m != nil {
		return m.NatIP
	}
	return ""
}

func (m *NbsAddr) GetNatPort() int32 {
	if m != nil {
		return m.NatPort
	}
	return 0
}

func init() {
	proto.RegisterType((*NbsAddr)(nil), "net.pb.NbsAddr")
}

func init() { proto.RegisterFile("nbsAddr.proto", fileDescriptor_b059c628fec3ac7c) }

var fileDescriptor_b059c628fec3ac7c = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xcf, 0x3d, 0x8e, 0xc2, 0x30,
	0x10, 0x86, 0x61, 0x79, 0x97, 0xfc, 0x59, 0xa2, 0xb1, 0x28, 0xa6, 0xa0, 0x88, 0xa8, 0x52, 0xa5,
	0xe1, 0x04, 0x94, 0x6e, 0x50, 0x14, 0x4e, 0x10, 0x13, 0x17, 0x11, 0x92, 0x6d, 0x0d, 0x13, 0x38,
	0x29, 0xf7, 0x41, 0x1e, 0x1b, 0xa5, 0x7c, 0xe7, 0x7b, 0x5c, 0x58, 0xee, 0x9d, 0x79, 0x5e, 0xe6,
	0x19, 0xfb, 0x80, 0x9e, 0xbc, 0x2a, 0x9d, 0xa5, 0x3e, 0x98, 0xd3, 0x47, 0xc8, 0xea, 0x9a, 0x16,
	0x75, 0x94, 0x8d, 0xb3, 0xf4, 0xf6, 0xf8, 0xd0, 0x33, 0x88, 0x56, 0x74, 0xcd, 0xb8, 0x1d, 0xe2,
	0x7a, 0x9f, 0xdc, 0xcd, 0xe2, 0xcb, 0x22, 0xfc, 0xb5, 0xa2, 0xab, 0xc7, 0xed, 0xa0, 0x0e, 0xb2,
	0x08, 0xab, 0xd1, 0x01, 0xfe, 0xf9, 0x5d, 0x0a, 0x05, 0xb2, 0x0a, 0xab, 0x19, 0x3c, 0x12, 0xec,
	0x5a, 0xd1, 0x15, 0xe3, 0x2f, 0xd9, 0xe3, 0xa2, 0x03, 0x14, 0xd9, 0xc7, 0x60, 0x8f, 0x0b, 0xfb,
	0x32, 0xfb, 0x94, 0xd1, 0xbb, 0x89, 0xf4, 0x00, 0x55, 0xf2, 0x1c, 0xd1, 0xbb, 0x89, 0xd8, 0xd7,
	0xc9, 0xe7, 0x34, 0x25, 0x7f, 0xf3, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x14, 0x23, 0xb3, 0x4a,
	0xf7, 0x00, 0x00, 0x00,
}
