// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package nat_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestType int32

const (
	RequestType_KAReq     RequestType = 0
	RequestType_inviteReq RequestType = 1
)

var RequestType_name = map[int32]string{
	0: "KAReq",
	1: "inviteReq",
}

var RequestType_value = map[string]int32{
	"KAReq":     0,
	"inviteReq": 1,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}

func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{0}
}

type ResponseType int32

const (
	ResponseType_KARes      ResponseType = 0
	ResponseType_inviteRes  ResponseType = 1
	ResponseType_invitedRes ResponseType = 2
)

var ResponseType_name = map[int32]string{
	0: "KARes",
	1: "inviteRes",
	2: "invitedRes",
}

var ResponseType_value = map[string]int32{
	"KARes":      0,
	"inviteRes":  1,
	"invitedRes": 2,
}

func (x ResponseType) String() string {
	return proto.EnumName(ResponseType_name, int32(x))
}

func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{1}
}

type Request struct {
	ReqType              RequestType    `protobuf:"varint,1,opt,name=reqType,proto3,enum=nat.pb.RequestType" json:"reqType,omitempty"`
	KeepAlive            *RegRequest    `protobuf:"bytes,2,opt,name=keepAlive,proto3" json:"keepAlive,omitempty"`
	Invite               *InviteRequest `protobuf:"bytes,3,opt,name=invite,proto3" json:"invite,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetReqType() RequestType {
	if m != nil {
		return m.ReqType
	}
	return RequestType_KAReq
}

func (m *Request) GetKeepAlive() *RegRequest {
	if m != nil {
		return m.KeepAlive
	}
	return nil
}

func (m *Request) GetInvite() *InviteRequest {
	if m != nil {
		return m.Invite
	}
	return nil
}

type Response struct {
	ResType              ResponseType    `protobuf:"varint,1,opt,name=resType,proto3,enum=nat.pb.ResponseType" json:"resType,omitempty"`
	KeepAlive            *RegResponse    `protobuf:"bytes,2,opt,name=keepAlive,proto3" json:"keepAlive,omitempty"`
	Invite               *InviteResponse `protobuf:"bytes,3,opt,name=invite,proto3" json:"invite,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResType() ResponseType {
	if m != nil {
		return m.ResType
	}
	return ResponseType_KARes
}

func (m *Response) GetKeepAlive() *RegResponse {
	if m != nil {
		return m.KeepAlive
	}
	return nil
}

func (m *Response) GetInvite() *InviteResponse {
	if m != nil {
		return m.Invite
	}
	return nil
}

func init() {
	proto.RegisterEnum("nat.pb.RequestType", RequestType_name, RequestType_value)
	proto.RegisterEnum("nat.pb.ResponseType", ResponseType_name, ResponseType_value)
	proto.RegisterType((*Request)(nil), "nat.pb.request")
	proto.RegisterType((*Response)(nil), "nat.pb.response")
}

func init() { proto.RegisterFile("session.proto", fileDescriptor_3a6be1b361fa6f14) }

var fileDescriptor_3a6be1b361fa6f14 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0xdd, 0x8a, 0xd1, 0x4c, 0x6d, 0x89, 0x13, 0x95, 0xd0, 0x53, 0xe9, 0xc5, 0x52, 0xe8,
	0xa2, 0xf5, 0xe2, 0xb5, 0x47, 0xf1, 0x16, 0x7c, 0x81, 0xb6, 0x0e, 0x65, 0x51, 0x36, 0x9b, 0xcc,
	0x5a, 0xf0, 0x51, 0x3c, 0xf8, 0xae, 0x92, 0xfd, 0x43, 0x52, 0xbd, 0xed, 0xec, 0x7c, 0xbf, 0x9d,
	0x8f, 0x1d, 0x18, 0x31, 0x31, 0xab, 0x4a, 0x4b, 0xd3, 0x54, 0xb6, 0xc2, 0x44, 0x6f, 0xac, 0x34,
	0xdb, 0xc9, 0x95, 0xde, 0xd8, 0x92, 0xf6, 0x8a, 0x2d, 0x35, 0xbe, 0x35, 0xc9, 0x77, 0x95, 0xd6,
	0xb4, 0xb3, 0xcf, 0xfa, 0xa0, 0x2c, 0xf9, 0xcb, 0xd9, 0xb7, 0x80, 0xf3, 0x86, 0xea, 0x4f, 0x62,
	0x8b, 0x4b, 0x77, 0x7c, 0xfd, 0x32, 0x54, 0x88, 0xa9, 0x98, 0x8f, 0x57, 0xb9, 0xf4, 0xaf, 0xc9,
	0xd2, 0x13, 0x6d, 0xab, 0x8c, 0x0c, 0xde, 0x43, 0xfa, 0x4e, 0x64, 0xd6, 0x1f, 0xea, 0x40, 0xc5,
	0x60, 0x2a, 0xe6, 0xc3, 0x15, 0x76, 0x81, 0x7d, 0xc8, 0x94, 0x1d, 0x84, 0x4b, 0x48, 0x94, 0x1b,
	0x5e, 0x9c, 0x3a, 0xfc, 0x26, 0xe2, 0x5e, 0x29, 0x26, 0x02, 0x34, 0xfb, 0x11, 0x70, 0xd1, 0x10,
	0x9b, 0x4a, 0x33, 0xa1, 0x6c, 0xe5, 0xb8, 0x27, 0x77, 0xdd, 0xcd, 0xf2, 0x48, 0xb4, 0x73, 0x10,
	0x3e, 0xfc, 0xb7, 0xcb, 0x8f, 0xec, 0x7c, 0xa8, 0xaf, 0x27, 0xff, 0xe8, 0xdd, 0x46, 0x5e, 0x05,
	0xbd, 0x10, 0x09, 0xd4, 0xe2, 0x0e, 0x86, 0xbd, 0x8f, 0xc1, 0x14, 0xce, 0x5e, 0xd6, 0x25, 0xd5,
	0xd9, 0x09, 0x8e, 0x20, 0x8d, 0x99, 0x3a, 0x13, 0x8b, 0x27, 0xb8, 0xec, 0x4b, 0x46, 0x92, 0x8f,
	0x49, 0xce, 0x04, 0x8e, 0x01, 0x7c, 0xf9, 0xd6, 0xd6, 0x83, 0x6d, 0xe2, 0xb6, 0xf4, 0xf8, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xbf, 0xb0, 0xb9, 0x1c, 0xe6, 0x01, 0x00, 0x00,
}
