// Code generated by protoc-gen-go. DO NOT EDIT.
// source: broadcastKeys.proto

package bitswap_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BroadCastKey struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadCastKey) Reset()         { *m = BroadCastKey{} }
func (m *BroadCastKey) String() string { return proto.CompactTextString(m) }
func (*BroadCastKey) ProtoMessage()    {}
func (*BroadCastKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d79c28c4f26d7d79, []int{0}
}

func (m *BroadCastKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadCastKey.Unmarshal(m, b)
}
func (m *BroadCastKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadCastKey.Marshal(b, m, deterministic)
}
func (m *BroadCastKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadCastKey.Merge(m, src)
}
func (m *BroadCastKey) XXX_Size() int {
	return xxx_messageInfo_BroadCastKey.Size(m)
}
func (m *BroadCastKey) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadCastKey.DiscardUnknown(m)
}

var xxx_messageInfo_BroadCastKey proto.InternalMessageInfo

func (m *BroadCastKey) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*BroadCastKey)(nil), "bitswap.pb.BroadCastKey")
}

func init() { proto.RegisterFile("broadcastKeys.proto", fileDescriptor_d79c28c4f26d7d79) }

var fileDescriptor_d79c28c4f26d7d79 = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2a, 0xca, 0x4f,
	0x4c, 0x49, 0x4e, 0x2c, 0x2e, 0xf1, 0x4e, 0xad, 0x2c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x4a, 0xca, 0x2c, 0x29, 0x2e, 0x4f, 0x2c, 0xd0, 0x2b, 0x48, 0x52, 0x52, 0xe2, 0xe2, 0x71,
	0x02, 0x29, 0x71, 0x86, 0x28, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4e, 0xad, 0x2c, 0x96, 0x60, 0x54,
	0x60, 0xd6, 0xe0, 0x0c, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0xda, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x9b, 0x66, 0x52, 0xe0, 0x4d, 0x00, 0x00, 0x00,
}
