// Code generated by protoc-gen-go. DO NOT EDIT.
// source: unixfs.proto

package unixfs_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data_DataType int32

const (
	Data_Raw       Data_DataType = 0
	Data_Directory Data_DataType = 1
	Data_File      Data_DataType = 2
	Data_Metadata  Data_DataType = 3
	Data_Symlink   Data_DataType = 4
	Data_HAMTShard Data_DataType = 5
)

var Data_DataType_name = map[int32]string{
	0: "Raw",
	1: "Directory",
	2: "File",
	3: "Metadata",
	4: "Symlink",
	5: "HAMTShard",
}
var Data_DataType_value = map[string]int32{
	"Raw":       0,
	"Directory": 1,
	"File":      2,
	"Metadata":  3,
	"Symlink":   4,
	"HAMTShard": 5,
}

func (x Data_DataType) String() string {
	return proto.EnumName(Data_DataType_name, int32(x))
}
func (Data_DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_unixfs_7720b98d85f6ec4c, []int{0, 0}
}

type Data struct {
	Type                 Data_DataType `protobuf:"varint,1,opt,name=Type,proto3,enum=unixfs.pb.Data_DataType" json:"Type,omitempty"`
	Data                 []byte        `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	DataLen              int64         `protobuf:"varint,3,opt,name=DataLen,proto3" json:"DataLen,omitempty"`
	Filesize             int64         `protobuf:"varint,4,opt,name=filesize,proto3" json:"filesize,omitempty"`
	HashType             int32         `protobuf:"varint,5,opt,name=hashType,proto3" json:"hashType,omitempty"`
	Fanout               int64         `protobuf:"varint,6,opt,name=fanout,proto3" json:"fanout,omitempty"`
	Blocksizes           []int64       `protobuf:"varint,7,rep,packed,name=blocksizes,proto3" json:"blocksizes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_unixfs_7720b98d85f6ec4c, []int{0}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetType() Data_DataType {
	if m != nil {
		return m.Type
	}
	return Data_Raw
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Data) GetDataLen() int64 {
	if m != nil {
		return m.DataLen
	}
	return 0
}

func (m *Data) GetFilesize() int64 {
	if m != nil {
		return m.Filesize
	}
	return 0
}

func (m *Data) GetHashType() int32 {
	if m != nil {
		return m.HashType
	}
	return 0
}

func (m *Data) GetFanout() int64 {
	if m != nil {
		return m.Fanout
	}
	return 0
}

func (m *Data) GetBlocksizes() []int64 {
	if m != nil {
		return m.Blocksizes
	}
	return nil
}

type Metadata struct {
	MimeType             string   `protobuf:"bytes,1,opt,name=MimeType,proto3" json:"MimeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_unixfs_7720b98d85f6ec4c, []int{1}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "unixfs.pb.Data")
	proto.RegisterType((*Metadata)(nil), "unixfs.pb.Metadata")
	proto.RegisterEnum("unixfs.pb.Data_DataType", Data_DataType_name, Data_DataType_value)
}

func init() { proto.RegisterFile("unixfs.proto", fileDescriptor_unixfs_7720b98d85f6ec4c) }

var fileDescriptor_unixfs_7720b98d85f6ec4c = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x71, 0x9d, 0xe6, 0xe7, 0x12, 0x90, 0x75, 0x07, 0x64, 0x31, 0xa0, 0x28, 0x03, 0xca,
	0x80, 0x32, 0xc0, 0x13, 0x20, 0x55, 0x88, 0x81, 0x2c, 0x6e, 0xc5, 0xee, 0xb4, 0x8e, 0x62, 0x35,
	0x4d, 0xaa, 0xc4, 0x15, 0x84, 0x47, 0xe2, 0x29, 0x91, 0x5d, 0x12, 0x58, 0x6c, 0x7d, 0x3e, 0xe7,
	0x5c, 0x5f, 0x1d, 0x88, 0x4f, 0xad, 0xfe, 0xac, 0x86, 0xfc, 0xd8, 0x77, 0xa6, 0xc3, 0x68, 0xa2,
	0x32, 0xfd, 0x5e, 0x80, 0xb7, 0x92, 0x46, 0xe2, 0x03, 0x78, 0x9b, 0xf1, 0xa8, 0x38, 0x49, 0x48,
	0x76, 0xfd, 0xc8, 0xf3, 0xd9, 0x92, 0x5b, 0xd9, 0x1d, 0x56, 0x17, 0xce, 0x85, 0x78, 0x4e, 0xf1,
	0x45, 0x42, 0xb2, 0x58, 0x9c, 0x27, 0x70, 0x08, 0xec, 0xfd, 0xa6, 0x5a, 0x4e, 0x13, 0x92, 0x51,
	0x31, 0x21, 0xde, 0x42, 0x58, 0xe9, 0x46, 0x0d, 0xfa, 0x4b, 0x71, 0xcf, 0x49, 0x33, 0x5b, 0xad,
	0x96, 0x43, 0xed, 0xfe, 0x5e, 0x26, 0x24, 0x5b, 0x8a, 0x99, 0xf1, 0x06, 0xfc, 0x4a, 0xb6, 0xdd,
	0xc9, 0x70, 0xdf, 0xa5, 0x7e, 0x09, 0xef, 0x00, 0xca, 0xa6, 0xdb, 0xee, 0xed, 0x80, 0x81, 0x07,
	0x09, 0xcd, 0xa8, 0xf8, 0xf7, 0x92, 0xbe, 0x43, 0x38, 0xed, 0x8b, 0x01, 0x50, 0x21, 0x3f, 0xd8,
	0x05, 0x5e, 0x41, 0xb4, 0xd2, 0xbd, 0xda, 0x9a, 0xae, 0x1f, 0x19, 0xc1, 0x10, 0xbc, 0x17, 0xdd,
	0x28, 0xb6, 0xc0, 0x18, 0xc2, 0x42, 0x19, 0xb9, 0x93, 0x46, 0x32, 0x8a, 0x97, 0x10, 0xac, 0xc7,
	0x43, 0xa3, 0xdb, 0x3d, 0xf3, 0x6c, 0xe6, 0xf5, 0xb9, 0xd8, 0xac, 0x6b, 0xd9, 0xef, 0xd8, 0x32,
	0xbd, 0xff, 0x73, 0xda, 0xbd, 0x0b, 0x7d, 0x50, 0x73, 0x67, 0x91, 0x98, 0xb9, 0xf4, 0x5d, 0xcd,
	0x4f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x90, 0x62, 0x70, 0x52, 0x76, 0x01, 0x00, 0x00,
}
